### PR TITLE
Migrate to Rust

### LINKED ISSUE #6: Perhaps use Rust instead of Python to avoid installation issues?
I hate to be that guy but I must be that guy now. It is for the greater good. I am sure that you understand:

"If you used Rust this would not be a problem.
Python is not that more productive than Rust after all."
-- That Guy

This statement only works though if all source is written in Rust. Mixes like with C++ always do not work well and drag in again all the bad things. Anyways. So I am aware that even if the devs wanted to it would not be an easy task at all. This is still worth as a general anti C++/Python message. And since I had to get through this installation none sense and this AI still does not work for me. I am afraid that you have now to listen to my dismay and other utter terror of lack of order for having dared to leave Rust lands.

I wrote plenty of lines of simple Rust source. Python is not going to be anymore productive than this so called "system language". Rust only sounds scary in its majestic title but is often used for a lot of things that got nothing to do with "system". Simple code in Rust is essentially like Java, C# or Python for that matter.

I do understand that these libraries are not only Python but also C++ which is the worst. However. It should be far more doable to get rid of Python first. Python is 31 years old. That is 310 years in silicon valley time. Rust had pattern matching since birth while Python only got it now for a year or so. It is time to upgrade and write real software. I do not see how Python/C++ could beat Rust's module system called Cargo and its database of Crates on crates.io. The only thing that might be a problem is the maturity of a Crate but certainly not the system itself.

I had a 1GB download for this "installation" just for some Python API. That is not how packing works, folks, That is how Python/C++ works. In Rust only the stuff used ends up in the binary. For Rust's Cargo itself an installation is not required either unlike with Conda. Rust's RustUp(Cargo/Compiler/Format/Doc, etc) is only used to for build time. You know. Like a real programming language for real software. Though this also goes back to C++ not only Python and its lack of an actual package system.

You can use Rust with VSCode easily too. No need for CLion or Visual Studio.

My own game logic/game engine project replaced C/C++/C# for good. GLSL and HLSL will be next. This treachery continues with GLSL and HLSL. And since I am also intending to use ML AI code for my own game beyond this text/image. That puts Python into my way again. Hence again a general anti C++/Python message. For higher level systems like a game you do not want to mess with a bazillion languages/APIs/tools if you can have only one. So this issue may not affect others as much as me. But now you are warned as to why I am not taking this lightly because I am the fool who as to learn and use: C/C++/C#/HLSL/GLSL/Python/Bison/Shmyson/Your Mom's Script

... and eventually yet another pile of **** that humanity made to solve one problem: How To Instruct A Computer To Do Things

I am not amused: -.-

My First Experience With Python

I hate to nag but I am afraid I have to share my initial experience with this productive programming language that I hear people talking about. And I have the feeling that more people will complain because AI is very wide spread these days and will spread way further. So way more people will get exposed to this.

As someone who also mods games I encountered many more languages than just C, C++, C#, F# , HLSL, GLSL, and of course Rust (One Language to Rule Them All) for game development. But I also for modding Java, Doom 3's C like script, World of Warcraft's LUA and now Python for so called scripting.

Judged by the time how long it takes(it still does not work for me) to execute simple code in txt2img.py(which should have been a CLI binary). Python by far is the worst thing I ever had to deal with in my entire life.

I tell you this: Lua and Python are a hoax like all non compiled languages. Their interpretive nature is of no good at all. Compiled languages like Java and C# are certainly better in all regards for so called scripting needs. Rust too actually.

Now to Python. After countless pip install commands One got 700MB of waste downloaded. Pure Rust source would pick only used code and compile it into the binary. No need for CMake or Condo which require their own install too again. One pip install imwatermark did install but not resolve its not found problem. I used a modified txt2img.py (taken from SD UI) without it and ran into a compilation error during startup. It says:
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(self.face_rec_model_path)?

I am sorry but what? Language versioning issues? A travesty like C/C++ at this point would have too already allowed me to execute its CLI binary. But not the productive language I hear so much about....

Python has no semicolons.
Maybe try F# instead of Python.

Python uses RETURN keyword. Rust does only in very special cases so mostly not at all.
Maybe try F# instead of Python.

Python uses GC. Rust has no GC and no simple code will require explicit life times to handle the Borrow Checker I think
Borrow Check is why Rust does not require a run time GC to handle memory automatically.
If you love GC try F#.

F# wins...

The list goes on with Python giving only then to take more back. That is not productive. That is a hoax. C and C++ does actually a similar thing with its compile times. They fool new programmers by giving the impression that they are easier to learn than Rust. Which is true for a Hello World+. But. Only then to force you to do debugging later(or handling dependencies later) during the worst time which is run time.

That is why Rust has a much steeper learning curve than C and C++ but it flattens out later to a C# and Java level of ease and productivity. Though the compile times are still rather long with longer code. Seems though the Rust compiler does not do multi threading much so there is room for improvement at least. But I am not hoaxing. Honestly Rust compiler ALWAYS will be at least a bit slower than all other compilers because it simply does more during that stage. Good thing that AMD is making faster CPUs these days... But frankly it is not that bad because it creates a massive amount of certainty that other languages do not provide.

Conclusion (2022/October/03)

This is all you have?

One half is chatbots.
The other half is off topic comments that got nothing to do with any kind of language so are off topic spam.

This is what your degree of "higher education" can produced regarding the languages Rust and your very own language Python that you know so much about?

You can not control what you do not understand. But spam is not hard to understand.... You are doomed...

### PR DESCRIPTION
**Pull request by Snapstromegon**
I believe that #6 contained many valid points and because of that I want to contribute the migration to rust. As @TheSamDickey mentioned, this is not an easy switch, but will likely improve the situation for all users and even more so the energy consumption.

The only possible downsides from a professional point of view right now are a requried build step for execution (handled easily via `cargo run --release`) and a slightly increased code complexity, which should be okay.

This PR introduces [rust](https://www.rust-lang.org/) as a dependency for the project. Use [rustup](https://rustup.rs/) to install it in a convenient way.

closes #6

### CODE REVIEW

**Comment by floppydisken** [comment]
The performance implications of staying close to the metal will be beneficial for the project overall. Arguably Rust is as readable as Python but *blazingly fast*. I second this PR.

**Review by Yetiowner — CHANGES_REQUESTED** [review]
A: I will only make changes recommended on r/programmerhumour
B: Even if I didn't, there is a major functionality flaw. See src/main.rs line 2: You misspelled HelloWorld

**Comment by Snapstromegon** [comment]
For anyone stumbling upon this: You can currently vote for this PR here: https://www.reddit.com/r/ProgrammerHumor/comments/y6iuto/comment/isx7ask/?utm_source=share&utm_medium=web2x&context=3

**Comment by james2432** [comment]
ew no

**Comment by TheSamDickey** [comment]
Brilliant!  This is a profound contribution that will be without a doubt impactful. I cannot imagine how many sleepless nights were sacrificed to accomplish such a high achievement.

Kudos!

**Pull request closed without merging**
